### ISSUE TITLE
Model.save

### ISSUE THREAD

**Issue by shyuep** [materialsvirtuallab/veidt#10]
These should be implemented properly. For example, the NeuralNetwork right now only saves the model but not the scaler. I am not sure how to save the Linear one. 

There should be a corresponding load.

**Comment by adengz** [comment]
For linear models, one can simply retrieve the coefficients and intercept from `lr.coef_` and `lr.intercept_` respectively after fitting. I suppose that would be enough?

**Comment by shyuep** [comment]
Yes, but you should be able to save those coeficients to a json file, and reload the exact same model from the file?
