### ISSUE TITLE
Move cache functionality to abstract Model class

### ISSUE THREAD

**Issue by chc273** [materialsvirtuallab/veidt#12]
Right now, the cache ability is defined every time we have a new `Model` class that inherits from the abstract class.  
I think this is rather inefficient and perhaps we can write a `cache` method in the abstract class?

Now I think the reason that limits us to do it is that the `fit` method takes `inputs` as arguments, and convert the `inputs` into `features` **inside** the `fit` method, rather than the `fit` method takes the converted `features` as the arguments. 

Or we can write `fit_from_features` method to the abstract class?

**Comment by shyuep** [comment]
Go ahead.
