### ISSUE TITLE
StandardScaler in NeuralNet model changes during every fitting

### ISSUE THREAD

**Issue by chc273** [materialsvirtuallab/veidt#13]
Usually the `fit` will be called multiple times during fitting the model (whenever we have new data, we can feed them into the model to update the weights). We want to keep the `StandardScaler` the same after the first time it is fitted. The current implementation uses `fit_transform` method of `StandardScaler` every time the `fit` method is called. This will update the preprocessing object every time and will give inconsistent results.

**Comment by w6ye** [comment]
So the scaler process can be made into a new method separately and saved  separately

**Comment by shyuep** [comment]
This is an easy fix. Just set the scaler to None initially. During the first fit, you do a fit_transform. If the scaler is not none, you then do a fit only.
