### ISSUE TITLE
A Veidt class that that combines descriptor and model

### ISSUE THREAD

**Issue by chc273** [materialsvirtuallab/veidt#28]
I think model should be independent of the descriptor, but sometimes we want them to be together as a whole when running the model predictions. This combination comes in handy when we predict properties directly on a structure. 

Previously, the combination was achieved by having describer as a pass-in argument to the model. I think in this way the flexibility of the model is reduced when we want to test the effect of different descriptors but keep the model fixed, or we want to test the effect of different models but keep the descriptor fixed. 

A third class that joins a model class and a descriptor class may make things more flexible. We may call it `Veidt`

**Comment by shyuep** [comment]
I don't quite understand. When you change the descriptor, the model has to be refitted anyway. So why would we want to combine the two?

**Comment by chc273** [comment]
Say we have a model and a descriptor, and we want to train on a (structures, energies) dataset. I agree that we can use the descriptor to convert structures into features and then feed (features, energies) to the model for the training. Next time if I want to predict the energy of one structure, I should repeat the structure->feature process and then feed feature to the same model.

If I have a third Veidt class that contains a descriptor and a model, I can wrap things within this one class, for example, training a model with (structures, energies) pairs directly, save and load consistent model+descriptor pairs for reproducibility. It also helps if I want to change the model, descriptor or the parameters for any process and rerun the training. I can just change the model or descriptor attribute of the Veidt instance, and rerun the entire process with one click, instead of repeating the structure conversion and model fitting process separately. 

Everything could be done in the existing setting, but I think having a Veidt class can make modeling easier in situations listed above.

**Comment by shyuep** [comment]
I am still not getting what you are proposing. You are saying that we should have a class that wraps a Desrcriber and a Model. That is already achieved by the Model class today, which takes in a Describer. 

If you want the Model class to take in raw feature values, that can be done by adding a new function to the Model class that simply feeds the raw features to the internal model.

Perhaps you can give me actual psuedo-code examples of what you want to achieve in the new class. Then I can comment on whether it is necessary (or good code design).

**Comment by chc273** [comment]
Yes, it can be done with the Model class today. 

For example, we want to run kernel ridge regression model on structures with bispectrum descriptor, currently the implementation would be like the following:

```
bispectrum = BispectrumDescriber(params_bs)
krr = KernelRidgeRegression(params_krr, describer=bispectrum) 

krr.fit_structures(structures, energies) # fit (structures, energies) dataset
new_energy = krr.predict_structures([new_structure]) # predict energy of a new structure

```
I think normally the model KernelRidgeRegression itself should exist independently without bispectrum descriptor. 

My thinking is as follows:

```
krr = KernelRidgeRegression(params_krr)
bispectrum = BispectrumDescriber(params_bs)

veidt = Veidt(model=krr, describer=bispectrum, ...) # the class that combines model and describer

veidt.train(structures, energies, ...) # train the model

# change the model parameter and retrain the model
veidt.model.param = new_param 
veidt.train(structures, energies)

# save and load consistent model+describer
veidt.save(filename)
veidt.load(filename)
```

**Comment by shyuep** [comment]
I think what you want is already the concept for the current Model class. E.g., you cna do something like

```
nn = NeuralNet(layer_sizes, describer)
nn.fit(structures, energies)
```

To change parameters (e.g., let's switch the layer sizes and activation function) and retrain,

```
nn.layer_sizes = [1, 2]
nn.activation = 'tanh'
nn.fit(structures, energies)
```

What is the difference between my code and your proposed class? 

The only part that is not in the current Model class is that it does not save the Describer during the save and load methods. But you can certainly fix that without introducing a new class.
