### ISSUE TITLE
Major code cleanup to adopt sklearn API

### ISSUE THREAD

**Issue by adengz** [materialsvirtuallab/veidt#32]
This is related to #26. Basically, there are two types of classes in `sklearn`, namely transformer and estimator. Essentially, the `Describer` class here is a type of transformer that converts pmg objects to numerical data. `sklearn` comes with `Pipeline` class that chains multiple transformers and an estimator (optional) to integrate the entire model construction process, which means both `MultiDescriber` and `Model` classes here are not necessarily needed. 

This is in line with the spirit of `matminer` (from my guess) that we should focus on materials science and leave the model fitting to other professional packages.

**Comment by shyuep** [comment]
I agree we should leave the actual mechanics of model fitting to other professional packages. So we are not actually implementing neural networks, regression trees, etc. ourselves. That said, I think there is a lot to be said for an overlay that simplifies the model fitting for materials science purposes. 

Nothing is actually "needed". You can start coding from numpy. You can do without pymatgen and just write scripts to manipulate POSCAR files line by line. If I took that attitude, some of the codes you are using today will not exist.
