### ISSUE TITLE
Support beyond one to one describing

### ISSUE THREAD

**Issue by adengz** [materialsvirtuallab/veidt#4]
Right now, the describer only returns a 1D feature array for an input object. 

An example of one to more describing, structure -> property of each site.

**Comment by shyuep** [comment]
OK. I don't think the current framework prevents that right?

**Comment by adengz** [comment]
No it doesn't. But the problem here is for one to more describing, one has to concatenate those 2D descriptions into a long pd.DataFrame or np.array.

**Comment by shyuep** [comment]
That's fine.

Basically, you need a describe_inputs and describe_outputs breakdown. By default, describe_outputs should just return outputs unchanged.
