### ISSUE TITLE
Code used to train the random forest models

### ISSUE THREAD

**Issue by mretegan** [materialsvirtuallab/veidt#76]
I would like to use `CenvPrediction` class for compounds that do not have a trained random forest model. Would it be possible to add to the repository an example of how such a model was trained? Thanks!

**Comment by mretegan** [comment]
@chc273 thanks for the quick reply. I've only asked for the procedure to train a random forest model because I was under the impression that this is required for the 2018 npj Computational Materials paper.

**Comment by mretegan** [comment]
Ok, so for the performance test of the ELSIE algorithm you have taken and experimental spectrum, and you have recalculated the combined rank of all theoretical spectra having the same absorber?

**Comment by chc273** [comment]
Yes

**Comment by shyuep** [comment]
@mretegan You can actually test out the ELSIE algo using the Materials Project website (https://www.materialsproject.org/#apps/xas). This should work for *all species* (in so far that they have already been present in the ICSD at some point).

The random forest model is a CN prediction code that we have developed. This is something that we are finishing up a paper on (should be posted within the next week or so). Once the paper is posted, we will upload the code with examples and you will be able to use it.

**Comment by mretegan** [comment]
@shyuep @chc273 Thank you for the detailed explanations.
