### ISSUE TITLE
Add feature cache to model

### ISSUE THREAD

**Issue by adengz** [materialsvirtuallab/veidt#9]
Since the current implementation of `Model` is an integration of feature calculation and model training, I wonder if this is a good idea to have a feature cache (at least for training inputs). It is more of an efficiency concern, especially for simple (e.g., linear) models, sometimes one needs to perform iteration with weight variations. There is no need for recomputing the features as it might be the "rate limiting step".

**Comment by shyuep** [comment]
Good idea. Go ahead.
